### PR TITLE
added wait option

### PR DESCRIPTION
**Pull request by Marko298**
#16 Impements the wait option

### CODE REVIEW

**Comment by ohookins** [comment]
Hi @Marko298 have you considered using https://github.com/bugcrowd/ecs-commander/ ? That wraps up this command and the monitoring aspects so that it takes care of the entire lifecycle of the ECS service deployment. This particular repository is really just a component in the overall toolchain, so waiting as part of this command is not really appropriate.

**Comment by Marko298** [comment]
Hello, that sounds like exact tool I need, but when I open the link it says 404

**Comment by ohookins** [comment]
I'm not sure why the repo is not public (that's a harder problem to solve) but the package is published here: https://www.npmjs.com/package/@bugcrowd/ecs-commander

**Comment by Marko298** [comment]
Whether to merge this PR is up to you. We made a fork back then, so we are good

**Pull request closed without merging**
